# Generated by Django 5.1.2 on 2025-01-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_for_week', models.DecimalField(decimal_places=4, max_digits=10)),
                ('avg_for_month', models.DecimalField(decimal_places=4, max_digits=10)),
                ('week_sales', models.DecimalField(decimal_places=4, max_digits=10)),
                ('month_sales', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_sales', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'new_sales_data',
                'ordering': ['-order_date'],
                'managed': True,
            },
        ),
    ]
