# Generated by Django 5.1.2 on 2025-03-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
    ]
