# Generated by Django 5.1.2 on 2025-03-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0003_rename_name_product_pname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
