# Generated by Django 5.1.2 on 2025-03-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0004_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
